// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMumDz_yI4C9_1u9P8BgMe2mZ-e90PE4',
    appId: '1:598915872738:web:86e1672cfcc122ba17ebbb',
    messagingSenderId: '598915872738',
    projectId: 'solo-slides',
    authDomain: 'solo-slides.firebaseapp.com',
    storageBucket: 'solo-slides.appspot.com',
    measurementId: 'G-QHXHWX3K2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-TaI3a0jdGDnvLQTeN_SIHm_eqLa2LA',
    appId: '1:598915872738:android:7a542051c8d156bd17ebbb',
    messagingSenderId: '598915872738',
    projectId: 'solo-slides',
    storageBucket: 'solo-slides.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldCa8shlYoqgybK2CriVjC8YS4_3y1KA',
    appId: '1:598915872738:ios:64f3d5713c453b6b17ebbb',
    messagingSenderId: '598915872738',
    projectId: 'solo-slides',
    storageBucket: 'solo-slides.appspot.com',
    iosBundleId: 'com.soloslides.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldCa8shlYoqgybK2CriVjC8YS4_3y1KA',
    appId: '1:598915872738:ios:9ed633c963a3b7c717ebbb',
    messagingSenderId: '598915872738',
    projectId: 'solo-slides',
    storageBucket: 'solo-slides.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVMumDz_yI4C9_1u9P8BgMe2mZ-e90PE4',
    appId: '1:598915872738:web:ad2d1067a313125a17ebbb',
    messagingSenderId: '598915872738',
    projectId: 'solo-slides',
    authDomain: 'solo-slides.firebaseapp.com',
    storageBucket: 'solo-slides.appspot.com',
    measurementId: 'G-WL2XFZ3DHL',
  );
}
