name: app
description: "Solo Slides"
version: 1.0.0+1


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
