name: app
description: "Solo Slides"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  firebase_analytics: ^11.2.1
  google_generative_ai: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
